## This workflow will install Python dependencies, run tests and lint with a single version of Python
## For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs pyinstaller
          pipreqs . && pip install -r requirements.txt
          pyinstaller -i icon.ico -F easy_cal.py

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'easy_cal.zip'
          exclusions: 'config.ini dist/easy_cal.exe'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "easy_cal.zip"
          token: ${{ secrets.TOKEN }}
          name: ${{ github.run_id }}
          tag: ${{ github.run_id }}
          draft: true
