## This workflow will install Python dependencies, run tests and lint with a single version of Python
## For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application

on:
  push:
#    branches: [ "main" ]
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install chardet==4.0.0 xlrd==1.2.0 pyinstaller
          pyinstaller -i icon.ico -F easy_cal.py
          cp dist/easy_cal.exe .

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'easy_cal.zip'
          path: 'config.ini easy_cal.exe'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "easy_cal.zip"
          token: ${{ secrets.TOKEN }}
#          name: ${{ github.run_id }}
#          tag: ${{ github.run_id }}
